### ISSUE TITLE
How to cache the compressed responses?

### ISSUE THREAD

**Issue by adaboese** [fastify/fastify-compress#277]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I assume there is a not insignificant overhead of using compression.

Instead, it would be cheaper to cache (or even store on disk) copies of the compressed content.

Is there a hook or another method I could use to achieve this instead of cache-ing every asset adhoc?

**Comment by mcollina** [comment]
Generically, this is better done at the CDN/reverse proxy level by using the Cache-Control headers at the application level.
What makes caching the compressed data _hard_ for this module is knowing when to serve the cached response.

To know if we can serve the cached response, we need to hash the original version, but to do so, we need to have it fully in memory. If it is a _small payload_, it's likely better to transfer it uncompressed. Larger payloads usually _must_ be sent as stream; otherwise, it would exhaust the memory, but if they are streams, we won't know their full hash before we have read them fully.

**Comment by gurgunday** [comment]
See `precompressed`: https://github.com/fastify/fastify-static?tab=readme-ov-file#precompressed
